import resume1 from './CV.pdf';

export const candidates = [
  {
    avatar: 'https://e.radikal.host/2023/08/18/avatar.jpg',
    name: 'Сергей Казаков',
    jobTitle: 'Офис-менеджер',
    match: '100',
    textStatus: 'Интервью с @alexeeva',
    exp: 1,
    work: 'Сургут нефть',
    like: true,
    years: '32',
    letter: '',
    status: 'activeCandidates',
    tags: ['Москва', 'Удаленка', 'Офис', 'Что-то', 'И еще'],
    resume: resume1,
  },
  {
    avatar: 'https://e.radikal.host/2023/08/18/avatar.jpg',
    name: 'Константинов Константин',
    jobTitle: 'Стейт-менеджер',
    match: '90',
    textStatus: 'Интервью с @alexeeva',
    exp: 3,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '5',
    letter: '',
    status: 'activeCandidates',
    resume:
      'https://cors-anywhere.herokuapp.com/https://rdfo.ru/files/resume1a.pdf',
  },
  {
    avatar: 'link',
    name: 'Петров-Сидоров Иннокентий',
    jobTitle: 'Офис-менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 5,
    work: 'Сургут нефть',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Павел Смирнов',
    jobTitle: 'Водитель',
    match: '70',
    textStatus: 'Интервью с @alexeeva',
    exp: 6,
    work: 'Газпромнефть',
    like: false,
    years: '32',
    letter: '',
    status: 'rejectedCandidates',
  },
  {
    avatar: 'link',
    name: 'Красильников Петр',
    jobTitle: 'Продавец',
    match: '70',
    textStatus: 'Интервью с @alexeeva',
    exp: 9,
    work: 'МТС',
    like: false,
    years: '32',
    letter: '',
    status: 'rejectedCandidates',
  },
  {
    avatar: 'link',
    name: 'Моисеев Борис',
    jobTitle: 'Тракторист',
    match: '60',
    textStatus: 'Интервью с @alexeeva',
    exp: 11,
    work: 'Автоваз',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Горбунов Олег',
    jobTitle: 'Офис-менеджер',
    match: '50',
    textStatus: 'Интервью с @alexeeva',
    exp: 12,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Осипов Иван',
    jobTitle: 'Шахтёр',
    match: '40',
    textStatus: 'Интервью с @alexeeva',
    exp: 14,
    work: 'Липецкий НПЗ',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Абрамов Максим',
    jobTitle: 'Стоматолог',
    match: '30',
    textStatus: 'Интервью с @alexeeva',
    exp: 21,
    work: '55 Больница',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Харитонов Алексей',
    jobTitle: 'Офис-менеджер',
    match: '20',
    textStatus: 'Интервью с @alexeeva',
    exp: 22,
    work: 'Яндекс',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Максимов Максим',
    jobTitle: 'Консультант',
    match: '10',
    textStatus: 'Интервью с @alexeeva',
    exp: 23,
    work: 'Икея',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Беряев Сергей',
    jobTitle: 'Консультант',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 29,
    work: 'Сбербанк',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Голубёв Александр',
    jobTitle: 'Учитель',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 30,
    work: 'Школа 1000',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Федосеев Кирилл',
    jobTitle: 'Офис-менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 31,
    work: 'Офис',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Зимин Никита',
    jobTitle: 'Преподаватель',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 32,
    work: 'МГУ',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Сазонов Леонид',
    jobTitle: 'Водитель',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 33,
    work: 'Таксопарк 1',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Князев Игорь',
    jobTitle: 'Дворник',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 33,
    work: 'Москва',
    like: false,
    years: '32',
    letter: '',
    status: 'activeCandidates',
  },
];
