export const candidates = [
  {
    avatar: 'link',
    name: 'Сергей Каазков',
    jobTitle: 'Офис менеджер',
    match: '100',
    textStatus: 'Интервью с @alexeeva',
    exp: 1,
    work: 'Сургут нефть',
    like: false,
    years: '32',
    letter: '',
    status: 'activeCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин12313131',
    jobTitle: 'Офис менеджер',
    match: '90',
    textStatus: 'Интервью с @alexeeva',
    exp: 2,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'activeCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин2',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 3,
    work: 'Сургут нефть',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин3',
    jobTitle: 'Офис-менеджер',
    match: '70',
    textStatus: 'Интервью с @alexeeva',
    exp: 4,
    work: 'Сургут нефть',
    like: false,
    years: '32',
    letter: '',
    status: 'rejectedCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин31',
    jobTitle: 'Офис-менеджер',
    match: '70',
    textStatus: 'Интервью с @alexeeva',
    exp: 4,
    work: 'Сургут нефть',
    like: false,
    years: '32',
    letter: '',
    status: 'rejectedCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин4',
    jobTitle: 'Офис-менеджер',
    match: '60',
    textStatus: 'Интервью с @alexeeva',
    exp: 5,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин5',
    jobTitle: 'Офис менеджер',
    match: '50',
    textStatus: 'Интервью с @alexeeva',
    exp: 6,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин6',
    jobTitle: 'Офис менеджер',
    match: '40',
    textStatus: 'Интервью с @alexeeva',
    exp: 7,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин7',
    jobTitle: 'Офис менеджер',
    match: '30',
    textStatus: 'Интервью с @alexeeva',
    exp: 8,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин8',
    jobTitle: 'Офис менеджер',
    match: '20',
    textStatus: 'Интервью с @alexeeva',
    exp: 9,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин9',
    jobTitle: 'Офис менеджер',
    match: '10',
    textStatus: 'Интервью с @alexeeva',
    exp: 10,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин10',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 11,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин11',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 12,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин12',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 13,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин13',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 14,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин14',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 15,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'favoritesCandidates',
  },
  {
    avatar: 'link',
    name: 'Константинов Константин15',
    jobTitle: 'Офис менеджер',
    match: '80',
    textStatus: 'Интервью с @alexeeva',
    exp: 16,
    work: 'Сургутский нефтеперерабатывающий',
    like: false,
    years: '32',
    letter: '',
    status: 'activeCandidates',
  },
];
