export const vacancies = [
  {
    id: '01',
    title: 'Офис-менеджер',
    location: 'Москва',
    employer: 'UTM',
    salary: { min: 50, max: 66 },
    link: '/vacancy',
    candidatesQty: 146,
    tags: ['Офис', 'Полная занятость', 'от 1 года', 'MS Office'],
    deadline: '2023-08-31T03:24:00',
    status: 'activeVacancies',
  },
  {
    id: '02',
    title: 'Продукт-менеджер',
    location: 'Москва',
    employer: 'Мегафон',
    salary: { min: 50, max: 66 },
    link: '/vacancy',
    candidatesQty: 16,
    tags: ['Офис', 'Полная занятость', 'от 1 года', 'Power BI'],
    deadline: '2023-08-31T03:24:00',
    status: 'draftVacancies',
  },
  {
    id: '03',
    title: 'Менеджер по продажам',
    location: 'Санкт-Петербург',
    employer: 'АО Комита',
    salary: { min: 50, max: 66 },
    link: '/vacancy',
    candidatesQty: 24,
    tags: ['Офис', 'Полная занятость', 'от 1 года'],
    deadline: '2022-12-31T03:24:00',
    status: 'activeVacancies',
  },
  {
    id: '04',
    title: 'Java-Developer (Java SE)',
    location: 'Санкт-Петербург',
    employer: 'АО Комита',
    salary: { min: 50, max: 66 },
    link: '/vacancy',
    candidatesQty: 23,
    tags: ['Удаленно', 'Полная занятость', 'Senior', 'Java'],
    deadline: '2023-08-15T03:24:00',
    status: 'activeVacancies',
  },
  {
    id: '05',
    title: 'Водитель такси',
    location: 'Москва',
    employer: 'Яндекс.Еда',
    salary: { min: 50, max: 66 },
    link: '/vacancy',
    candidatesQty: 132,
    tags: ['Полная занятость', 'от 1 года'],
    deadline: '2023-08-31T03:24:00',
    status: 'completedVacancies',
  },
];
